# We are actually using unreleased features in capsule. Use 0.10 after it's released.
# capsule version
version = "0.9.1"
# path of deployment config file
deployment = "deployment.toml"

[rust]
workspace_dir = "contracts"

[[contracts]]
name = "ckb-std-tests"
template_type = "Rust"

[[contracts]]
name = "exec-callee"
template_type = "Rust"

[[contracts]]
name = "exec-callee-args"
template_type = "Rust"

[[contracts]]
name = "exec-caller"
template_type = "Rust"

[[contracts]]
name = "exec-caller-by-code-hash"
template_type = "Rust"

[[contracts]]
name = "exec-caller-args"
template_type = "Rust"

[[contracts]]
name = "spawn-caller"
template_type = "Rust"

[[contracts]]
name = "spawn-caller-by-code-hash"
template_type = "Rust"

[[contracts]]
name = "spawn-callee"
template_type = "Rust"
